/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game_JNIHandler */

#ifndef _Included_Game_JNIHandler
#define _Included_Game_JNIHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game_JNIHandler
 * Method:    initializeGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Game_JNIHandler_initializeGame
        (JNIEnv *, jobject);

/*
 * Class:     Game_JNIHandler
 * Method:    getSelectedPiece
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Game_JNIHandler_getSelectedPiece
        (JNIEnv *, jobject);

/*
 * Class:     Game_JNIHandler
 * Method:    handleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Game_JNIHandler_handleClick
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_JNIHandler
 * Method:    getPieceAt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Game_JNIHandler_getPieceAt
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_JNIHandler
 * Method:    getCurrentPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_JNIHandler_getCurrentPlayer
        (JNIEnv *, jobject);

/*
 * Class:     Game_JNIHandler
 * Method:    getWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_JNIHandler_getWinner
        (JNIEnv *, jobject);

/*
 * Class:     Game_JNIHandler
 * Method:    getChanges
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Game_JNIHandler_getChanges
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
